package cn.lzy.pojo;

public class People {

    private Integer id;
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.xuehaoid
     *
     * @mbg.generated
     */
    private Integer xuehaoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.classid
     *
     * @mbg.generated
     */
    private Integer classid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.id
     *
     * @return the value of people.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.id
     *
     * @param id the value for people.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.name
     *
     * @return the value of people.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.name
     *
     * @param name the value for people.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.xuehaoid
     *
     * @return the value of people.xuehaoid
     *
     * @mbg.generated
     */
    public Integer getXuehaoid() {
        return xuehaoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.xuehaoid
     *
     * @param xuehaoid the value for people.xuehaoid
     *
     * @mbg.generated
     */
    public void setXuehaoid(Integer xuehaoid) {
        this.xuehaoid = xuehaoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.classid
     *
     * @return the value of people.classid
     *
     * @mbg.generated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.classid
     *
     * @param classid the value for people.classid
     *
     * @mbg.generated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }
}